access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://rusiru960:p1MovyTLdvkHXwja@cluster0.skmc0i0.mongodb.net/test
logging:
  level:
    org.springframework.security: DEBUG
